export const OMNIROUTE_RESPONSE_HEADERS = {
  cache: "X-OmniRoute-Cache",
  cacheHit: "X-OmniRoute-Cache-Hit",
  compression: "X-OmniRoute-Compression",
  costSaved: "X-OmniRoute-Cost-Saved",
  decision: "X-OmniRoute-Decision",
  fallbackAttempts: "X-OmniRoute-Fallback-Attempts",
  latencyMs: "X-OmniRoute-Latency-Ms",
  model: "X-OmniRoute-Model",
  progress: "X-OmniRoute-Progress",
  provider: "X-OmniRoute-Provider",
  requestId: "X-OmniRoute-Request-Id",
  responseCost: "X-OmniRoute-Response-Cost",
  tokensIn: "X-OmniRoute-Tokens-In",
  tokensOut: "X-OmniRoute-Tokens-Out",
  version: "X-OmniRoute-Version",
} as const;
