/**
 * KIE image-provider model catalog — extracted from imageRegistry.ts
 * (god-file decomposition, mirrors the lmarena/directModels.ts pattern).
 * Pure data literal; imported by imageRegistry.ts. No behavior change.
 */
export const KIE_IMAGE_MODELS = [
  { id: "gpt4o-image", name: "KIE 4o Image" },
  { id: "seedream/4.5-text-to-image", name: "Seedream 4.5", isMarket: true },
  { id: "seedream/4.5-edit", name: "Seedream 4.5 Edit", isMarket: true },
  { id: "seedream/5.0-lite-text-to-image", name: "Seedream 5.0 Lite", isMarket: true },
  { id: "seedream/5.0-lite-image-to-image", name: "Seedream 5.0 Lite I2I", isMarket: true },
  { id: "z-image/4.0-text-to-image", name: "Z-Image v4.0", isMarket: true },
  { id: "z-image/4.5-text-to-image", name: "Z-Image v4.5", isMarket: true },
  { id: "google-imagen/imagen4-fast", name: "Imagen 4 Fast", isMarket: true },
  { id: "google-imagen/imagen4-ultra", name: "Imagen 4 Ultra", isMarket: true },
  { id: "google-imagen/imagen4", name: "Imagen 4", isMarket: true },
  { id: "google-imagen/nano-banana-2", name: "Nano Banana 2", isMarket: true },
  { id: "google-imagen/nano-banana", name: "Nano Banana", isMarket: true },
  { id: "google-imagen/nano-banana-pro", name: "Nano Banana Pro", isMarket: true },
  { id: "google-imagen/nano-banana-edit", name: "Nano Banana Edit", isMarket: true },
  { id: "flux/2-pro-image-to-image", name: "Flux 2 Pro I2I", isMarket: true },
  { id: "flux/2-pro-text-to-image", name: "Flux 2 Pro T2I", isMarket: true },
  { id: "flux/2-image-to-image", name: "Flux 2 I2I", isMarket: true },
  { id: "flux/2-text-to-image", name: "Flux 2 T2I", isMarket: true },
  { id: "flux/kontext", name: "Flux Kontext", isMarket: true },
  { id: "grok-imagine/text-to-image", name: "Grok Imagine T2I", isMarket: true },
  { id: "grok-imagine/image-to-image", name: "Grok Imagine I2I", isMarket: true },
  { id: "gpt/gpt-image-1.5-text-to-image", name: "GPT Image 1.5 T2I", isMarket: true },
  { id: "gpt/gpt-image-1.5-image-to-image", name: "GPT Image 1.5 I2I", isMarket: true },
  { id: "gpt/gpt-image-2-text-to-image", name: "GPT Image 2 T2I", isMarket: true },
  { id: "gpt/gpt-image-2-image-to-image", name: "GPT Image 2 I2I", isMarket: true },
  { id: "ideogram/v3-text-to-image", name: "Ideogram v3", isMarket: true },
  { id: "ideogram/v3-edit", name: "Ideogram v3 Edit", isMarket: true },
  { id: "ideogram/v3-remix", name: "Ideogram v3 Remix", isMarket: true },
  { id: "ideogram/v3-reframe", name: "Ideogram v3 Reframe", isMarket: true },
  { id: "qwen/text-to-image", name: "Qwen T2I", isMarket: true },
  { id: "qwen/image-to-image", name: "Qwen I2I", isMarket: true },
  { id: "qwen/image-edit", name: "Qwen Edit", isMarket: true },
  { id: "qwen2/image-edit", name: "Qwen2 Edit", isMarket: true },
  { id: "qwen2/text-to-image", name: "Qwen2 T2I", isMarket: true },
  { id: "wan/2.7-image", name: "Wan 2.7 Image", isMarket: true },
  { id: "wan/2.7-image-pro", name: "Wan 2.7 Image Pro", isMarket: true },
];
